// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Foo              string
	SchemaMigrations string
	SpatialRefSys    string
}{
	Foo:              "foo",
	SchemaMigrations: "schema_migrations",
	SpatialRefSys:    "spatial_ref_sys",
}
