// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Foos", testFoos)
	t.Run("SchemaMigrations", testSchemaMigrations)
	t.Run("SpatialRefSys", testSpatialRefSys)
}

func TestDelete(t *testing.T) {
	t.Run("Foos", testFoosDelete)
	t.Run("SchemaMigrations", testSchemaMigrationsDelete)
	t.Run("SpatialRefSys", testSpatialRefSysDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Foos", testFoosQueryDeleteAll)
	t.Run("SchemaMigrations", testSchemaMigrationsQueryDeleteAll)
	t.Run("SpatialRefSys", testSpatialRefSysQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Foos", testFoosSliceDeleteAll)
	t.Run("SchemaMigrations", testSchemaMigrationsSliceDeleteAll)
	t.Run("SpatialRefSys", testSpatialRefSysSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Foos", testFoosExists)
	t.Run("SchemaMigrations", testSchemaMigrationsExists)
	t.Run("SpatialRefSys", testSpatialRefSysExists)
}

func TestFind(t *testing.T) {
	t.Run("Foos", testFoosFind)
	t.Run("SchemaMigrations", testSchemaMigrationsFind)
	t.Run("SpatialRefSys", testSpatialRefSysFind)
}

func TestBind(t *testing.T) {
	t.Run("Foos", testFoosBind)
	t.Run("SchemaMigrations", testSchemaMigrationsBind)
	t.Run("SpatialRefSys", testSpatialRefSysBind)
}

func TestOne(t *testing.T) {
	t.Run("Foos", testFoosOne)
	t.Run("SchemaMigrations", testSchemaMigrationsOne)
	t.Run("SpatialRefSys", testSpatialRefSysOne)
}

func TestAll(t *testing.T) {
	t.Run("Foos", testFoosAll)
	t.Run("SchemaMigrations", testSchemaMigrationsAll)
	t.Run("SpatialRefSys", testSpatialRefSysAll)
}

func TestCount(t *testing.T) {
	t.Run("Foos", testFoosCount)
	t.Run("SchemaMigrations", testSchemaMigrationsCount)
	t.Run("SpatialRefSys", testSpatialRefSysCount)
}

func TestHooks(t *testing.T) {
	t.Run("Foos", testFoosHooks)
	t.Run("SchemaMigrations", testSchemaMigrationsHooks)
	t.Run("SpatialRefSys", testSpatialRefSysHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Foos", testFoosInsert)
	t.Run("Foos", testFoosInsertWhitelist)
	t.Run("SchemaMigrations", testSchemaMigrationsInsert)
	t.Run("SchemaMigrations", testSchemaMigrationsInsertWhitelist)
	t.Run("SpatialRefSys", testSpatialRefSysInsert)
	t.Run("SpatialRefSys", testSpatialRefSysInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Foos", testFoosReload)
	t.Run("SchemaMigrations", testSchemaMigrationsReload)
	t.Run("SpatialRefSys", testSpatialRefSysReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Foos", testFoosReloadAll)
	t.Run("SchemaMigrations", testSchemaMigrationsReloadAll)
	t.Run("SpatialRefSys", testSpatialRefSysReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Foos", testFoosSelect)
	t.Run("SchemaMigrations", testSchemaMigrationsSelect)
	t.Run("SpatialRefSys", testSpatialRefSysSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Foos", testFoosUpdate)
	t.Run("SchemaMigrations", testSchemaMigrationsUpdate)
	t.Run("SpatialRefSys", testSpatialRefSysUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Foos", testFoosSliceUpdateAll)
	t.Run("SchemaMigrations", testSchemaMigrationsSliceUpdateAll)
	t.Run("SpatialRefSys", testSpatialRefSysSliceUpdateAll)
}
